name: Archive Tumblr

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test Single Page Download
        run: |
          mkdir -p backup
          # Scarichiamo solo la home page per test
          curl -L "https://aasastroblog.tumblr.com/" -o backup/index.html
          echo "aasastro.com" > CNAME

      - name: Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Test backup" || exit 0
          git push origin main
