name: Archive Tumblr

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # <--- CONTROLLA CHE CI SIA QUESTA RIGA!

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
